name: Build and Publish Electron App

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Verify electron-builder config
        run: |
          node -e "const p=require('./package.json'); \
            console.log('singleArchFiles=', p?.build?.mac?.singleArchFiles || 'MISSING'); \
            console.log('x64ArchFiles=', p?.build?.mac?.x64ArchFiles || 'MISSING'); \
            if(!p?.build?.mac?.singleArchFiles || !p?.build?.mac?.x64ArchFiles) process.exit(1)"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
    
      - name: Setup macOS signing keychain
        run: |
          echo "${{ secrets.MAC_P12_BASE64 }}" | base64 --decode > certificate.p12
          security create-keychain -p "buildkey" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "buildkey" build.keychain
          security set-keychain-settings -lut 3600 build.keychain
          security import certificate.p12 -k build.keychain -P "${{ secrets.MAC_P12_PASSWORD }}" -T /usr/bin/codesign -T /usr/bin/productsign
          security set-key-partition-list -S apple-tool:,apple: -s -k "buildkey" build.keychain

      - name: Download and extract portable-python
        run: |
          curl -L --fail -o portable-python.zip https://github.com/RAGPIQ/ragpiq_link/releases/download/v2.1.75/portable-python.zip
          unzip -q portable-python.zip

      - name: Remove macOS quarantine attribute
        run: |
          xattr -dr com.apple.quarantine portable-python
      
      - name: List contents of unzipped portable-python
        run: |
          echo "📁 Current directory: $(pwd)"
          echo "🔍 Top level:"
          ls -la
          echo "📂 portable-python:"
          ls -la portable-python || echo "❌ portable-python not found"
          echo "📂 portable-python/mac:"
          ls -la portable-python/mac || echo "❌ portable-python/mac not found"
          echo "📂 Deep scan:"
          find portable-python | head -n 100

      - name: Verify portable-python/mac exists
        run: |
          ls -al portable-python
          ls -al portable-python/mac || (echo "❌ portable-python/mac not found" && exit 1)

      - name: Clean portable-python
        run: |
          set -euo pipefail
          find portable-python -name '__pycache__' -exec rm -rf {} +
          find portable-python -name '*.pyc' -delete
          find portable-python -name '*.pyo' -delete
          find portable-python -type d -name 'test*' -exec rm -rf {} +
          find portable-python -name '*.gif' -delete
          find portable-python -name '*.tcl' -delete
          find portable-python -name '*.png' -delete
          find portable-python -name '*.jpg' -delete
          find portable-python -name '*.jpeg' -delete
          find portable-python -name '*.txt' -delete
          find portable-python -name '*.rst' -delete
          find portable-python -name '*.md' -delete
          find portable-python -path '*/share/*' -exec rm -rf {} +
          find portable-python -path '*/doc/*' -exec rm -rf {} +

          find portable-python/mac -name '__pycache__' -exec rm -rf {} +
          find portable-python/mac -type f \( -name '*.pyc' -o -name '*.pyo' -o -name '*.py' -o -name '*.txt' -o -name '*.rst' -o -name '*.md' \) -delete
          find portable-python/mac -type d -name 'test*' -exec rm -rf {} +
          find portable-python/mac -type f \( -name '*.gif' -o -name '*.png' -o -name '*.tcl' -o -name '*.jpg' -o -name '*.jpeg' -o -name '*.tiff' -o -name '*.exe' -o -name '*.dll' -o -name '*.pyd' -o -name '*.bat' -o -name '*.pak' -o -name '*.icns' \) -delete
          find portable-python/mac -path '*/share/*' -exec rm -rf {} +
          find portable-python/mac -path '*/doc/*' -exec rm -rf {} +
          find portable-python/mac -name 'tclConfig.sh' -delete
          find portable-python/mac -name 'tclooConfig.sh' -delete
          find portable-python/mac -name '*.a' -delete
          find portable-python/mac -name 'tkConfig.sh' -delete
          find portable-python/mac -type f ! -name "*.dylib" ! -name "*.so" \
            ! -path "*/Library/Frameworks/3.13/bin/python3" \
            ! -path "*/Library/Frameworks/3.13/bin/python3.13" \
            ! -path "*/Library/Frameworks/3.13/bin/python3-config" \
            -exec chmod -x {} +

      - name: Build x64 app
        run: npx electron-builder --mac --x64 --publish=never
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CSC_NAME: ${{ secrets.CSC_NAME }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          NOTARIZE_APP_BUNDLE_ID: ${{ secrets.NOTARIZE_APP_BUNDLE_ID }}

      - name: Build arm64 app
        run: npx electron-builder --mac --arm64 --publish=never
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CSC_NAME: ${{ secrets.CSC_NAME }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          NOTARIZE_APP_BUNDLE_ID: ${{ secrets.NOTARIZE_APP_BUNDLE_ID }}

      - name: Build universal app
        run: npx electron-builder --mac --universal
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          CSC_NAME: ${{ secrets.CSC_NAME }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          NOTARIZE_APP_BUNDLE_ID: ${{ secrets.NOTARIZE_APP_BUNDLE_ID }}

      - name: Upload macOS Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/**/Ragpiq*.dmg
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Download and extract portable-python
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://github.com/RAGPIQ/ragpiq_link/releases/download/v2.1.75/portable-python.zip" -OutFile "portable-python.zip"
          Expand-Archive -Path "portable-python.zip" -DestinationPath "."

      - name: Build Windows app
        run: npx electron-builder --win --x64
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload Windows Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/**/Ragpiq*.exe
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}